# Generated by Django 5.1.1 on 2024-09-30 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimg',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='categoriaimg',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='productoimg',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogImg',
        ),
        migrations.DeleteModel(
            name='CategoriaImg',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='ProductoImg',
        ),
    ]
