# Generated by Django 5.1.1 on 2024-09-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_categoria_imgcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='img',
            field=models.ImageField(null=True, upload_to='media/FotoPrincipal'),
        ),
    ]
